# GLOBAL PARAMETER
global:
  namespace: shop
  replicaCount: 1
  clusterName: my-cluster
  env: K8S-DEV
  productName: cnk

shop:
  frontend: 
    name: frontend
    app: frontend
    port: 9990
    image: yuyatinnefeld/cnk-frontend
    imageTag: 1.1.0
    description: "CKN FRONTEND"
    serviceTypes: LoadBalancer
    http:
      name: http-frontend

  backendInventory:
    name: backend-inventory
    app: inventory
    port: 9991
    image: yuyatinnefeld/cnk-backend-inventory
    imageTag: 1.1.0
    description: "CKN BACKEND INVENTORY"
    serviceTypes: LoadBalancer
    http:
      name: http-inventory

  backendML:
    name: backend-ml
    app: ml
    port: 9992
    image: yuyatinnefeld/cnk-backend-ml
    imageTag: 1.1.0
    description: "CKN BACKEND ML"
    serviceTypes: LoadBalancer
    http:
      name: http-ml

istio:
  gateway:
    name: cnk-gateway
    port: 80
    hostname: "gateway.cnk.com"