apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fortio.service.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.fortio.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.fortio.labels.app }}
    spec:
      containers:
      - name: {{ .Values.fortio.labels.app }}
        image: "{{ .Values.fortio.image.repository }}:{{ .Values.fortio.image.tag }}"
        imagePullPolicy: {{ .Values.fortio.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.fortio.service.port }}
