apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    app:  {{ .Values.shop.frontend.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  {{ .Values.shop.frontend.app }}
  template:
    metadata:
      labels:
        app:  {{ .Values.shop.frontend.app }}
    spec:
      containers:
        - name: {{ .Values.shop.frontend.app }}
          image: {{ .Values.shop.frontend.image }}:{{ .Values.shop.frontend.imageTag }}
          env:
            - name: APP_NAME
              value: "CKN FRONTEND"
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.shop.frontend.port }}