apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shop.frontend.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.shop.frontend.app }}
  ports:
    - port: {{ .Values.shop.frontend.port }}
      targetPort: {{ .Values.shop.frontend.port }}
      name: {{ .Values.shop.frontend.http.name }}
  type: {{ .Values.shop.frontend.serviceTypes }}
