apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: {{ .Values.istio.gateway.port }}
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.istio.gateway.hostname }}