apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  # annotations:
  #   argocd.argoproj.io/sync-wave: "3"
  name: cnk-virtualservice
  namespace: {{ .Values.global.namespace }}
spec:
  hosts:
  - {{ .Values.istio.gateway.hostname }}
  gateways:
  - {{ .Values.istio.gateway.name }}
  http:
  - match:
    - uri:
        exact: /
    - uri:
        exact: /health
    - uri:
        prefix: /fetch-item # Call Inventory API
    - uri:
        prefix: /ml # Call Inventory API -> ML API
    route:
    - destination:
        port:
          number: {{ .Values.shop.frontend.port }}
        host: {{ .Values.global.productName }}-{{ .Values.shop.frontend.name }}
  - match:
    - uri:
        prefix: /backend-inventory
    route:
    - destination:
        port:
          number: {{ .Values.shop.backendInventory.port }}
        host: {{ .Values.global.productName }}-{{ .Values.shop.backendInventory.name }}