apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pullsecret-demo
  namespace: shop
spec:
  secretStoreRef:
    kind: SecretStore
    name: vault-secret-store
  refreshInterval: 60s
  target:
    name: pulled-secret-from-vault
  data:
    - secretKey: password
      remoteRef:
        key: kv/data/test-pullsecret
        property: password
    - secretKey: username
      remoteRef:
        key: kv/data/test-pullsecret
        property: username