apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-demo
  namespace: shop
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 60s
  secretStoreRefs:
    - name: vault-secret-store
      kind: SecretStore
  selector:
    secret:
      name: pulled-secret-from-vault
  template:
    metadata:
      annotations:
        networking.istio.io/cluster: my-cluster
      labels:
        istio/multiCluster: 'true'
  data:
    - match:
        remoteRef:
          remoteKey: kv/data/test-pushsecret