apiVersion: apps/v1
kind: Deployment
metadata:
  # annotations:
  #   argocd.argoproj.io/sync-wave: "4"
  name: {{ .Values.global.productName }}-{{ .Values.api.external.name }}
  namespace: {{ .Values.api.external.namespace }}
  labels:
    app:  {{ .Values.api.external.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  {{ .Values.api.external.app }}
  template:
    metadata:
      labels:
        app:  {{ .Values.api.external.app }}
    spec:
      containers:
        - name: {{ .Values.api.external.app }}
          image: {{ .Values.api.external.image }}:{{ .Values.api.external.imageTag }}
          env:
            - name: APP_NAME
              value: {{ .Values.api.external.description }}
            - name: VERSION
              value: {{ .Values.api.external.imageTag }}
            - name: ENV
              value: {{ .Values.global.env }}
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.api.external.port }}
            initialDelaySeconds: 5
            periodSeconds: 10