apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  labels:
    helm.sh/chart: grafana-8.5.8
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "11.2.2-security-01"
    app.kubernetes.io/managed-by: Helm
  name: grafana
  namespace: {{ .Values.global.namespace }}
