apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali
  namespace: {{ .Values.global.namespace }}
  labels:
    helm.sh/chart: kiali-server-2.1.0
    app: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali
    version: "v2.1.0"
    app.kubernetes.io/version: "v2.1.0"
    app.kubernetes.io/part-of: "kiali"