apiVersion: batch/v1
kind: Job
metadata:
  generateName: testkube-testworkflows-execution
  namespace: istio-testapp
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: execute-testworkflows
        image: kubeshop/testkube-cli:2.1.19
        command:
        - /bin/sh
        - -c
        - |
          testkube get tw
      restartPolicy: Never