{{- range .Values.hw.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-{{ .version }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $.Values.hw.labels.app }}
    version: {{ .version }}
spec:
  replicas: {{ $.Values.global.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Values.hw.labels.app }}
      version: {{ .version }}
  template:
    metadata:
      labels:
        app: {{ $.Values.hw.labels.app }}
        version: {{ .version }}
    spec:
      containers:
        - name: dest-container-{{ .version }}
          image: {{ $.Values.hw.image.repository }}:{{ $.Values.hw.image.tag }}
          args: {{ .args }}
          ports:
            - containerPort: {{ $.Values.hw.service.containerPort }}
      {{- if $.Values.istio.injectSidecar }}
      annotations:
        sidecar.istio.io/inject: "true"
      {{- end }}
{{- end }}