apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hw.service.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.hw.labels.app }}
spec:
  selector:
    app: {{ .Values.hw.labels.app }}
  ports:
    - port: {{ .Values.hw.service.port }}
      targetPort: {{ .Values.hw.service.targetPort }}
      name: http-{{ .Values.hw.labels.app }}
      protocol: {{ .Values.hw.service.protocol }}
  type: {{ .Values.hw.service.type }}
