apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-v1
  namespace: {{ .Values.global.namespace }}
  labels:
    version: v1
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.hw.labels.app }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Values.hw.labels.app }}
        version: v1
    spec:
      containers:
      - name: dest-container-v1
        image: "{{ .Values.hw.image.repository }}:{{ .Values.hw.image.tag }}"
        args:
          - "-text=APP: HW-V1 | NS: istio-testapp | CLUSTER: my-cluster" # TODO: Update with ArgoCD Parameter
        ports:
        - containerPort: {{ .Values.hw.service.port }}