apiVersion: v1
kind: Service
metadata:
  name: kiali
  namespace: {{ .Values.global.namespace }}
  labels:
    helm.sh/chart: kiali-server-2.1.0
    app: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali
    version: "v2.1.0"
    app.kubernetes.io/version: "v2.1.0"
    app.kubernetes.io/part-of: "kiali"
  annotations:
spec:
  ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 20001
  - name: http-metrics
    appProtocol: http
    protocol: TCP
    port: 9090
  selector:
    app.kubernetes.io/name: kiali
    app.kubernetes.io/instance: kiali