apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: cnk-shop-pool
  namespace: {{ .Values.global.namespace }}
spec:
  addresses:
  - 172.18.0.150-172.18.0.200
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: cnk-shop-l2adversement
  namespace: {{ .Values.global.namespace }}
spec:
  ipAddressPools:
  - cnk-shop-pool