apiVersion: v1
kind: Namespace
metadata:
  name: istio-testapp
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-gateways
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-monitor