apiVersion: v1
kind: Service
metadata:
  name: hw-svc
  namespace: istio-testapp
  labels:
    app: hw
spec:
  selector:
    app: hw
  ports:
    - port: 7777
      name: "http-hw"
      targetPort: 5678
      protocol: TCP
  type: LoadBalancer
---
###############
# destination v1 
###############
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-v1
  namespace: istio-testapp
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw
      version: v1
  template:
    metadata:
      labels:
        app: hw
        version: v1
    spec:
      containers:
        - name: dest-countainer-v1
          image: hashicorp/http-echo
          args:
            - "-text=APP: HW-V1 | NS: istio-testapp | CLUSTER: north-cluster" # TODO: Update with helm values.yaml "$CLUSTER_NAME" # 
          ports:
            - containerPort: 7777
---
###############
# destination v2
###############
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-v2
  namespace: istio-testapp
  labels:
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw
      version: v2
  template:
    metadata:
      labels:
        app: hw
        version: v2
    spec:
      containers:
        - name: dest-countainer-v1
          image: hashicorp/http-echo
          args:
            - "-text=APP: HW-V2 | NS: istio-testapp | CLUSTER: north-cluster" # TODO: Update with helm values.yaml "$CLUSTER_NAME" # 
          ports:
            - containerPort: 7777