# GLOBAL PARAMETER
global:
  namespace: istio-testapp
  replicaCount: 1

# ISTIO PARAMETER
istio:
  injection: enabled
  injectSidecar: true

# TARGET APP PARAMETER
httpbin:
  image:
    repository: docker.io/mccutchen/go-httpbin
    tag: v2.15.0
    pullPolicy: IfNotPresent
  service:
    name: httpbin
    port: 8080
    targetPort: 8080
  serviceAccount:
    name: httpbin
  labels:
    app: httpbin
    version: v1

sleep:
  image:
    repository: curlimages/curl
    pullPolicy: IfNotPresent
    tag: latest
  serviceAccount:
    name: sleep
  service:
    type: ClusterIP
    port: 80
  labels:
    app: sleep
  secretName: sleep-secret
