apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.productName }}-{{ .Values.shop.backendInventory.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.shop.backendInventory.app }}
  ports:
    - port: {{ .Values.shop.backendInventory.port }}
      targetPort: {{ .Values.shop.backendInventory.port }}
      name: {{ .Values.shop.backendInventory.http.name }}
  type: {{ .Values.shop.frontend.serviceTypes }}
