apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: {{ .Values.global.productName }}-{{ .Values.shop.frontend.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app:  {{ .Values.shop.frontend.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  {{ .Values.shop.frontend.app }}
  template:
    metadata:
      labels:
        app:  {{ .Values.shop.frontend.app }}
    spec:
      containers:
        - name: {{ .Values.shop.frontend.app }}
          image: {{ .Values.shop.frontend.image }}:{{ .Values.shop.frontend.imageTag }}
          env:
            - name: APP_NAME
              value: {{ .Values.shop.frontend.description }}
            - name: VERSION
              value: {{ .Values.shop.frontend.imageTag }}
            - name: ENV
              value: {{ .Values.global.env }}
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.shop.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10