apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-applicationset-testkube-jobs
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: "my-cluster"
  template:
    metadata:
      name: "testkube"
    spec:
      project: default
      source:
        repoURL: https://kubeshop.github.io/helm-charts
        chart: testkube
        targetRevision: 2.1.55
        helm:
          releaseName: testkube
          parameters:
          - name: createNamespace
            value: "true"
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: testkube
      syncPolicy:
        automated:
          prune: true
          selfHeal: true