apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-applicationset-eso
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: "my-cluster"
  template:
    metadata:
      name: "eso"
    spec:
      source:
        repoURL: https://charts.external-secrets.io
        chart: external-secrets
        targetRevision: 0.11.0
        helm:
          releaseName: external-secrets
          parameters:
          - name: createNamespace
            value: "true"
      project: default
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: external-operator-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true