apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-app
  namespace: argocd
spec:
  template:
    metadata:
      name: "test-argocd-app"
    spec:
      project: default
      source:
        repoURL: "https://github.com/yuyatinnefeld/microservice-kiosk.git"
        targetRevision: HEAD
        path: app/helm
        helm:
          valueFiles:
            - values.yaml
          parameters:
            - name: project
              value: "argocd-project"
            - name: stage
              value: "argocd-stage"
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
