apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-applicationset-cnk-shop
  namespace: shop
spec:
  generators:
    - list:
        elements:
          - cluster: "my-cluster"
  template:
    metadata:
      name: "cnk-shop"
    spec:
      sources:
        - repoURL: "https://github.com/yuyatinnefeld/microservice-kiosk.git"
          path: vault/helm
          helm:
            valueFiles:
              - values.yaml
      project: default
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: vault-secrets-operator-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true