apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: {{ .Values.shop.frontend.name }}-sa
  namespace: {{ .Values.global.namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-sa-token
  namespace: {{ .Values.global.namespace }}
  annotations:
    kubernetes.io/service-account.name: frontend-sa
type: kubernetes.io/service-account-token