name: 🚀 Build Image Pipeline
run-name: build-image

on:
  workflow_dispatch:
    inputs:
      frontend_version:
        description: Frontend version
        default: 0.1.0
        required: true
      backend_version:
        description: Inventory version
        default: 0.1.0
        required: true
env:
  DOCKER_HUB_NAMESPACE: yuyatinnefeld
  FRONTEND_IMAGE_NAME: cnk-frontend
  INVENTORY_IMAGE_NAME: cnk-backend-inventory
  FRONTEND_CONTEXT: app/shop/component/frontend
  BACKEND_CONTEXT: app/shop/component/inventory

jobs:
  push_to_registry:
    name: Push Images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Check Out Repository
        uses: docker/setup-qemu-action@v1

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.FRONTEND_CONTEXT }}
          push: true
          tags: ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ github.event.inputs.frontend_version }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.BACKEND_CONTEXT }}
          push: true
          tags: ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.INVENTORY_IMAGE_NAME }}:${{ github.event.inputs.backend_version }}
