name: 🚀 Build Image Pipeline
run-name: build-image

on:
  workflow_dispatch:
    inputs:
      frontend_version:
        description: Frontend version
        default: 0.1.0
        required: true
      backend_version:
        description: Inventory version
        default: 0.1.0
        required: true
env:
  DOCKER_HUB_NAMESPACE: yuyatinnefeld
  FRONTEND_IMAGE_NAME: microservice-kiosk-frontend
  INVENTORY_IMAGE_NAME: microservice-kiosk-backend-inventory

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: push-frontend-image
        uses: docker/build-push-action@v2
        with:
          context: app/frontend/
          push: true
          tags: ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ github.event.inputs.frontend_version }}

      - name: push-backend-inventory-image
        uses: docker/build-push-action@v2
        with:
          context: app/inventory/
          push: true
          tags: ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.INVENTORY_IMAGE_NAME }}:${{ github.event.inputs.backend_version }}
