apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fortio.service.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.fortio.labels.app }}
  ports:
  - protocol: TCP
    port: {{ .Values.fortio.service.port }}
    targetPort: {{ .Values.fortio.service.targetPort }}
